---
# ./roles/redis/tasks/setup-Debian.yml

- name: Проверить, что пользователя petya не существует и удалить его, если существует (модуль user).
  user:
    name: petya
    state: absent
    remove: yes
