---
- name: Создать директории (если их нет) /var/www, назначить владельцем пользователя www и группу www (модуль file).
  become: yes
  ansible.builtin.file:
    path: /var/www
    state: directory
    owner: www
    group: www

- name: Создать директории (если их нет) /var/www_backup, назначить владельцем пользователя www и группу www (модуль file).
  become: yes
  ansible.builtin.file:
    path: /var/www_backup
    state: directory
    owner: www
    group: www
