---
- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /opt/distr
    state: directory
    mode: '0777'
  tags:
  - config

- name: Скопировать скачанный дистрибутив средствами Ansible на целевой хост (модуль copy).
  ansible.builtin.copy:
    src: distribReactApp.zip
    dest: /opt/distr/distribReactApp.zip
  tags:
  - config
